let today = new Date();
console.log(today);
console.log(today.getDate());
console.log(today.getMonth());
console.log(today.getDay());
console.log(today.getFullYear());
console.log(today.getHours());
console.log(today.getMinutes());
console.log(today.getSeconds());
console.log(today.getMilliseconds());
console.log(today.getTime());
console.log(today.getTimezoneOffset());
console.log(today.toISOString());
console.log(today.toDateString());
console.log(today.toTimeString());